#!/usr/bin/env bash
# 01-create-clickops-estate.sh
#
# Simulates the "ClickOps estate" — a small set of Azure resources created
# directly in the portal/CLI, with no Terraform behind them. Demo 1 then
# imports these into Terraform to prove "every resource you import is one
# more resource that's recoverable from code".
#
# Pre-reqs:
#   - az login, optionally with --tenant for your Azure tenant
#   - az account show points at the right subscription
#
# Output: writes ./resource-ids.env with the generated names and resource IDs.
# Source it before running terraform query.

set -euo pipefail

LOCATION="${LOCATION:-australiaeast}"
PREFIX="${PREFIX:-searchdemo}"
DEMO_TAG="${DEMO_TAG:-search-import-demo}"
SUFFIX="${SUFFIX:-$(date +%s | tail -c 5)}"

RG_NAME="${PREFIX}-rg-${SUFFIX}"
SA_NAME="${PREFIX}sa${SUFFIX}"   # storage account: lowercase, no hyphens, <= 24
VNET_NAME="${PREFIX}-vnet-${SUFFIX}"

echo "==> Creating resource group: ${RG_NAME}"
az group create \
  --name "${RG_NAME}" \
  --location "${LOCATION}" \
  --tags created_by=clickops demo="${DEMO_TAG}" owner=demo.operator \
  -o none

echo "==> Creating storage account: ${SA_NAME}"
az storage account create \
  --name "${SA_NAME}" \
  --resource-group "${RG_NAME}" \
  --location "${LOCATION}" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --tags created_by=clickops demo="${DEMO_TAG}" \
  -o none

echo "==> Creating vnet: ${VNET_NAME}"
az network vnet create \
  --name "${VNET_NAME}" \
  --resource-group "${RG_NAME}" \
  --location "${LOCATION}" \
  --address-prefixes 10.42.0.0/16 \
  --subnet-name default \
  --subnet-prefixes 10.42.1.0/24 \
  --tags created_by=clickops demo="${DEMO_TAG}" \
  -o none

echo "==> Resolving resource IDs"
RG_ID=$(az group show --name "${RG_NAME}" --query id -o tsv)
SA_ID=$(az storage account show --name "${SA_NAME}" --resource-group "${RG_NAME}" --query id -o tsv)
VNET_ID=$(az network vnet show --name "${VNET_NAME}" --resource-group "${RG_NAME}" --query id -o tsv)

cat > "$(dirname "$0")/../resource-ids.env" <<EOF
# Generated by 01-create-clickops-estate.sh on $(date -u +%FT%TZ)
export TF_VAR_rg_name="${RG_NAME}"
export TF_VAR_sa_name="${SA_NAME}"
export TF_VAR_vnet_name="${VNET_NAME}"
export TF_VAR_location="${LOCATION}"
export TF_VAR_demo_tag="${DEMO_TAG}"

export RG_ID="${RG_ID}"
export SA_ID="${SA_ID}"
export VNET_ID="${VNET_ID}"
EOF

cat <<EOF

==> Done. Created 3 resources in subscription: $(az account show --query name -o tsv)

  Resource group : ${RG_NAME}
  Storage account: ${SA_NAME}
  Virtual network: ${VNET_NAME}

Next:
  source ./resource-ids.env
  cd terraform/
  terraform init
  terraform query
  terraform query -generate-config-out=generated.tf
EOF
