#!/usr/bin/env bash
# 02-bootstrap-tfc-oidc.sh
#
# Wires up TFC dynamic provider credentials for Azure (OIDC federation).
# Replaces the client-secret pattern. After this runs, the HCP Terraform
# workspace authenticates to Azure with a short-lived OIDC token — no
# long-lived secret stored in TFC.
#
# What this creates in Azure:
#   1. An Azure AD application + service principal
#   2. Two federated identity credentials on the app, trusting TFC's OIDC
#      issuer for the plan and apply run phases of this specific workspace
#   3. A Contributor role assignment on the subscription
#
# What it prints at the end:
#   The exact HCP Terraform workspace env vars to set.
#
# Pre-reqs:
#   - az login, optionally with --tenant for your Azure tenant
#   - az account show points at the subscription you want TFC to manage
#   - You have Application Administrator (or Owner) in the tenant
#   - You have User Access Administrator (or Owner) on the subscription

set -euo pipefail

# -- Inputs --------------------------------------------------------------------
TFC_ORG="${TFC_ORG:-}"
TFC_PROJECT="${TFC_PROJECT:-Default Project}"
TFC_WORKSPACE="${TFC_WORKSPACE:-search-import-demo}"
APP_DISPLAY_NAME="${APP_DISPLAY_NAME:-tfc-${TFC_WORKSPACE}}"
TFC_HOSTNAME="${TFC_HOSTNAME:-app.terraform.io}"

if [ -z "${TFC_ORG}" ]; then
  echo "TFC_ORG is required. Example: TFC_ORG=my-org ./scripts/02-bootstrap-tfc-oidc.sh" >&2
  exit 1
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
TENANT_ID=$(az account show --query tenantId -o tsv)

echo "==> Settings"
echo "    TFC org/project/workspace: ${TFC_ORG} / ${TFC_PROJECT} / ${TFC_WORKSPACE}"
echo "    Azure subscription:        $(az account show --query name -o tsv) (${SUBSCRIPTION_ID})"
echo "    Azure tenant:              ${TENANT_ID}"
echo "    AAD app display name:      ${APP_DISPLAY_NAME}"
echo

# -- 1. Azure AD application + service principal -------------------------------
echo "==> Creating Azure AD application: ${APP_DISPLAY_NAME}"
APP_ID=$(az ad app list --display-name "${APP_DISPLAY_NAME}" --query "[0].appId" -o tsv)
if [ -z "${APP_ID}" ]; then
  APP_ID=$(az ad app create --display-name "${APP_DISPLAY_NAME}" --query appId -o tsv)
  echo "    Created app: ${APP_ID}"
else
  echo "    Reusing existing app: ${APP_ID}"
fi

OBJECT_ID=$(az ad app show --id "${APP_ID}" --query id -o tsv)

echo "==> Ensuring service principal exists for app"
SP_ID=$(az ad sp list --filter "appId eq '${APP_ID}'" --query "[0].id" -o tsv)
if [ -z "${SP_ID}" ]; then
  SP_ID=$(az ad sp create --id "${APP_ID}" --query id -o tsv)
  echo "    Created SP: ${SP_ID}"
else
  echo "    Reusing existing SP: ${SP_ID}"
fi

# -- 2. Federated identity credentials (one per run phase) ---------------------
# Subject format that TFC issues:
#   organization:<ORG>:project:<PROJECT>:workspace:<WS>:run_phase:<plan|apply>
# Issuer: https://app.terraform.io  (or your TFE hostname)
# Audience: api://AzureADTokenExchange
create_fic () {
  local phase="$1"
  local name="${TFC_WORKSPACE}-${phase}"
  local subject="organization:${TFC_ORG}:project:${TFC_PROJECT}:workspace:${TFC_WORKSPACE}:run_phase:${phase}"

  echo "==> Federated credential: ${name}"
  echo "    subject: ${subject}"

  if az ad app federated-credential list --id "${APP_ID}" --query "[?name=='${name}']" -o tsv | grep -q .; then
    echo "    Already exists, skipping create"
    return
  fi

  az ad app federated-credential create \
    --id "${APP_ID}" \
    --parameters "$(cat <<JSON
{
  "name": "${name}",
  "issuer": "https://${TFC_HOSTNAME}",
  "subject": "${subject}",
  "audiences": ["api://AzureADTokenExchange"],
  "description": "TFC dynamic credentials for ${TFC_ORG}/${TFC_WORKSPACE} (${phase})"
}
JSON
)" -o none
}

create_fic plan
create_fic apply

# -- 3. Role assignment --------------------------------------------------------
echo "==> Granting Contributor on subscription to SP ${SP_ID}"
if az role assignment list --assignee "${APP_ID}" --scope "/subscriptions/${SUBSCRIPTION_ID}" \
     --query "[?roleDefinitionName=='Contributor']" -o tsv | grep -q .; then
  echo "    Already assigned, skipping"
else
  az role assignment create \
    --assignee "${APP_ID}" \
    --role Contributor \
    --scope "/subscriptions/${SUBSCRIPTION_ID}" \
    -o none
fi

# -- 4. Emit TFC workspace env vars --------------------------------------------
cat > "$(dirname "$0")/../tfc-oidc.env" <<EOF
# Generated by 02-bootstrap-tfc-oidc.sh on $(date -u +%FT%TZ)
# Set these as ENV-category variables on the TFC workspace
# ${TFC_ORG}/${TFC_WORKSPACE}.

# Tells the azurerm provider (via TFC's dynamic credentials helper) to use OIDC.
TFC_AZURE_PROVIDER_AUTH=true

# The Azure AD app/client ID that TFC will impersonate via OIDC.
TFC_AZURE_RUN_CLIENT_ID=${APP_ID}

# Standard azurerm provider env vars.
ARM_TENANT_ID=${TENANT_ID}
ARM_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
ARM_USE_OIDC=true
EOF

cat <<EOF

==> Done.

Set the following ENV-category variables on workspace ${TFC_ORG}/${TFC_WORKSPACE}:

  TFC_AZURE_PROVIDER_AUTH = true
  TFC_AZURE_RUN_CLIENT_ID = ${APP_ID}
  ARM_TENANT_ID           = ${TENANT_ID}
  ARM_SUBSCRIPTION_ID     = ${SUBSCRIPTION_ID}
  ARM_USE_OIDC            = true

Also written to: ./tfc-oidc.env

Then in HCP Terraform, queue a plan. The provider will exchange a TFC-issued
OIDC token for an Azure AD access token at run time — no client secret needed.

Reference: https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials/azure-configuration
EOF
